### ISSUE TITLE
Analytics & SEO

### ISSUE THREAD

**Issue by DimiBaitanciuc** [ThemeFuse/Unyson-Analytics-Extension#1]
Ce-ar fi sa renuntam la extensia de Analytics si sa includem optiunea http://joxi.ru/BA0bnqQcPpP0my in extensia SEO, si sa-i zicem Analytics & SEO. Ma gandeam ca pentru o singura optiune la analytics nu face sens sa avem o extensie separata.

**Comment by sergiubagrin** [comment]
Analytics acum nu are nimic dar se presupune ca pe viitor va avea si alte optiuni va desena grafice.

**Comment by DimiBaitanciuc** [comment]
Inteleg face sens perfect atunci sa fie separat.
